apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-config-map
  namespace: netdata-auto-discovery
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"

    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so

    TypesConfig conf/mime.types
    User daemon
    Listen 0.0.0.0:80
    DirectoryIndex index.html
    ErrorLog /proc/self/fd/2
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    DocumentRoot "/usr/local/apache2/htdocs"

    <Directory />
      AllowOverride None
      Require all denied
    </Directory>

    <Directory "/usr/local/apache2/htdocs">
      Options Indexes FollowSymLinks
      AllowOverride None
      Require all granted
    </Directory>

    <Location /server-status>
      SetHandler server-status
    </Location>
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: netdata-auto-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      component: httpd
  template:
    metadata:
      labels:
        component: httpd
    spec:
      volumes:
        - name: config
          configMap:
            name: httpd-config-map
      containers:
        - name: httpd
          image: httpd
          resources:
            requests:
              cpu: 1m
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
