apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: netdata-service-discovery-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 1m
          ports:
            - containerPort: 6379
