apiVersion: v1
kind: ServiceAccount
metadata:
  name: netdata-bouncer-service-account
  namespace: netdata-service-discovery-lab

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: netdata-bouncer-role
  namespace: netdata-service-discovery-lab
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - list
      - get
      - update
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netdata-bouncer-role-binding
  namespace: netdata-service-discovery-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: netdata-bouncer-role
subjects:
  - kind: ServiceAccount
    name: netdata-bouncer-service-account
    namespace: netdata-service-discovery-lab

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouncer
  namespace: netdata-service-discovery-lab
  labels:
    skipBounce: skip
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bouncer
  template:
    metadata:
      labels:
        component: bouncer
    spec:
      serviceAccountName: netdata-bouncer-service-account
      containers:
        - name: bouncer
          image: ilyam8/k8s-deployment-bouncer
          resources:
            requests:
              cpu: 1m
          env:
            - name: BOUNCE_EVERY
              value: "30"

---
